<?php

return [
    'instrumento_convocatorio' => [
        1 => 'Edital',
        2 => 'Aviso de Contratação Direta',
        3 => 'Ato que autoriza a Contratação Direta',
    ],

    'modalidade_de_contratacao' => [
        1 => 'Leilão Eletrônico',
        2 => 'Diálogo Competitivo',
        3 => 'Concurso',
        4 => 'Concorrência Eletrônica',
        5 => 'Concorrência Presencial',
        6 => 'Pregão Eletrônico',
        7 => 'Pregão Presencial',
        8 => 'Dispensa de Licitação',
        9 => 'Inexigibilidade',
        10 => 'Manifestação de Interesse',
        11 => 'Pré-qualificação',
        12 => 'Credenciamento',
        13 => 'Leilão - Presencial',
    ],

    'modo_de_disputa' => [
        1 => 'Aberto',
        2 => 'Fechado',
        3 => 'Aberto-Fechado',
        4 => 'Dispensa com Disputa',
        5 => 'Não se aplica',
        6 => 'Fechado-Aberto',
    ],

    'criterio_de_julgamento' => [
        1 => 'Menor preço',
        2 => 'Maior desconto',
        4 => 'Técnica e preço',
        5 => 'Maior lance',
        6 => 'Maior retorno econômico',
        7 => 'Não se aplica',
        8 => 'Melhor técnica',
        9 => 'Conteúdo artístico',
    ],

    'situacao_da_contratacao' => [
        1 => 'Divulgada no PNCP',
        2 => 'Revogada',
        3 => 'Anulada',
        4 => 'Suspensa',
    ],

    'situacao_do_item_da_contratacao' => [
        1 => 'Em Andamento',
        2 => 'Homologado',
        3 => 'Anulado/Revogado/Cancelado',
        4 => 'Deserto',
        5 => 'Fracassado',
    ],

    'tipo_de_beneficio' => [
        1 => 'Participação exclusiva para ME/EPP',
        2 => 'Subcontratação para ME/EPP',
        3 => 'Cota reservada para ME/EPP',
        4 => 'Sem benefício',
        5 => 'Não se aplica',
    ],

    'situacao_do_resultado_do_item_da_contratacao' => [
        1 => 'Informado',
        2 => 'Cancelado',
    ],

    'tipo_de_contrato' => [
        1 => 'Contrato (termo inicial)',
        2 => 'Comodato',
        3 => 'Arrendamento',
        4 => 'Concessão',
        5 => 'Termo de Adesão',
        6 => 'Convênio',
        7 => 'Empenho',
        8 => 'Outros',
        9 => 'Termo de Execução Descentralizada (TED)',
        10 => 'Acordo de Cooperação Técnica (ACT)',
        11 => 'Termo de Compromisso',
        12 => 'Carta Contrato',
    ],

    'tipo_de_termo_de_contrato' => [
        1 => 'Termo de Rescisão',
        2 => 'Termo Aditivo',
        3 => 'Termo de Apostilamento',
    ],

    'categoria_do_processo' => [
        1 => 'Cessão',
        2 => 'Compras',
        3 => 'Informática (TIC)',
        4 => 'Internacional',
        5 => 'Locação Imóveis',
        6 => 'Mão de Obra',
        7 => 'Obras',
        8 => 'Serviços',
        9 => 'Serviços de Engenharia',
        10 => 'Serviços de Saúde',
        11 => 'Alienação de bens móveis/imóveis',
    ],

    'tipo_de_documento_da_contratacao' => [
        1 => 'Aviso de Contratação Direta',
        2 => 'Edital',
        3 => 'Minuta do Contrato',
        4 => 'Termo de Referência',
        5 => 'Anteprojeto',
        6 => 'Projeto Básico',
        7 => 'Estudo Técnico Preliminar',
        8 => 'Projeto Executivo',
        9 => 'Mapa de Riscos',
        10 => 'DOD',
    ],

    'tipo_de_documento_ata_de_registro_de_preco' => [
        11 => 'Ata de Registro de Preço',
    ],

    'tipo_de_documento_de_contrato' => [
        12 => 'Contrato',
        13 => 'Termo de Rescisão',
        14 => 'Termo Aditivo',
        15 => 'Termo de Apostilamento',
        16 => 'Nota de Empenho',
    ],

    'natureza_juridica' => [
        '0000' => 'Natureza Jurídica não informada',
        '1015' => 'Órgão Público do Poder Executivo Federal',
        '1023' => 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal',
        '1031' => 'Órgão Público do Poder Executivo Municipal',
        '1040' => 'Órgão Público do Poder Legislativo Federal',
        '1058' => 'Órgão Público do Poder Legislativo Estadual ou do Distrito Federal',
        '1066' => 'Órgão Público do Poder Legislativo Municipal',
        '1074' => 'Órgão Público do Poder Judiciário Federal',
        '1082' => 'Órgão Público do Poder Judiciário Estadual',
        '1104' => 'Autarquia Federal',
        '1112' => 'Autarquia Estadual ou do Distrito Federal',
        '1120' => 'Autarquia Municipal',
        '1139' => 'Fundação Pública de Direito Público Federal',
        '1147' => 'Fundação Pública de Direito Público Estadual ou do Distrito Federal',
        '1155' => 'Fundação Pública de Direito Público Municipal',
        '1163' => 'Órgão Público Autônomo Federal',
        '1171' => 'Órgão Público Autônomo Estadual ou do Distrito Federal',
        '1180' => 'Órgão Público Autônomo Municipal',
        '1198' => 'Comissão Polinacional',
        '1210' => 'Consórcio Público de Direito Público (Associação Pública)',
        '1228' => 'Consórcio Público de Direito Privado',
        '1236' => 'Estado ou Distrito Federal',
        '1244' => 'Município',
        '1252' => 'Fundação Pública de Direito Privado Federal',
        '1260' => 'Fundação Pública de Direito Privado Estadual ou do Distrito Federal',
        '1279' => 'Fundação Pública de Direito Privado Municipal',
        '1287' => 'Fundo Público da Administração Indireta Federal',
        '1295' => 'Fundo Público da Administração Indireta Estadual ou do Distrito Federal',
        '1309' => 'Fundo Público da Administração Indireta Municipal',
        '1317' => 'Fundo Público da Administração Direta Federal',
        '1325' => 'Fundo Público da Administração Direta Estadual ou do Distrito Federal',
        '1333' => 'Fundo Público da Administração Direta Municipal',
        '1341' => 'União',
        '2011' => 'Empresa Pública',
        '2038' => 'Sociedade de Economia Mista',
        '2046' => 'Sociedade Anônima Aberta',
        '2054' => 'Sociedade Anônima Fechada',
        '2062' => 'Sociedade Empresária Limitada',
        '2070' => 'Sociedade Empresária em Nome Coletivo',
        '2089' => 'Sociedade Empresária em Comandita Simples',
        '2097' => 'Sociedade Empresária em Comandita por Ações',
        '2100' => 'Sociedade Mercantil de Capital e Indústria',
        '2127' => 'Sociedade em Conta de Participação',
        '2135' => 'Empresário (Individual)',
        '2143' => 'Cooperativa',
        '2151' => 'Consórcio de Sociedades',
        '2160' => 'Grupo de Sociedades',
        '2178' => 'Estabelecimento, no Brasil, de Sociedade Estrangeira',
        '2194' => 'Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira',
        '2216' => 'Empresa Domiciliada no Exterior',
        '2224' => 'Clube/Fundo de Investimento',
        '2232' => 'Sociedade Simples Pura',
        '2240' => 'Sociedade Simples Limitada',
        '2259' => 'Sociedade Simples em Nome Coletivo',
        '2267' => 'Sociedade Simples em Comandita Simples',
        '2275' => 'Empresa Binacional',
        '2283' => 'Consórcio de Empregadores',
        '2291' => 'Consórcio Simples',
        '2305' => 'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)',
        '2313' => 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)',
        '2321' => 'Sociedade Unipessoal de Advocacia',
        '2330' => 'Cooperativas de Consumo',
        '2348' => 'Empresa Simples de Inovação - Inova Simples',
        '2356' => 'Investidor Não Residente',
        '3034' => 'Serviço Notarial e Registral (Cartório)',
        '3069' => 'Fundação Privada',
        '3077' => 'Serviço Social Autônomo',
        '3085' => 'Condomínio Edilício',
        '3107' => 'Comissão de Conciliação Prévia',
        '3115' => 'Entidade de Mediação e Arbitragem',
        '3131' => 'Entidade Sindical',
        '3204' => 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras',
        '3212' => 'Fundação ou Associação Domiciliada no Exterior',
        '3220' => 'Organização Religiosa',
        '3239' => 'Comunidade Indígena',
        '3247' => 'Fundo Privado',
        '3255' => 'Órgão de Direção Nacional de Partido Político',
        '3263' => 'Órgão de Direção Regional de Partido Político',
        '3271' => 'Órgão de Direção Local de Partido Político',
        '3280' => 'Comitê Financeiro de Partido Político',
        '3298' => 'Frente Plebiscitária ou Referendária',
        '3301' => 'Organização Social (OS)',
        '3328' => 'Plano de Benefícios de Previdência Complementar Fechada',
        '3999' => 'Associação Privada',
        '4014' => 'Empresa Individual Imobiliária',
        '4090' => 'Candidato a Cargo Político Eletivo',
        '4120' => 'Produtor Rural (Pessoa Física)',
        '5010' => 'Organização Internacional',
        '5029' => 'Representação Diplomática Estrangeira',
        '5037' => 'Outras Instituições Extraterritoriais',
        '8885' => 'Natureza Jurídica não informada',
    ],

    'porte_da_empresa' => [
        1 => 'ME: Microempresa',
        2 => 'EPP: Empresa de pequeno porte',
        3 => 'Demais: Demais empresas',
    ],

    'amparo_legal' => [
        1 => 'Lei 14.133/2021, Art. 28, I',
        2 => 'Lei 14.133/2021, Art. 28, II',
        3 => 'Lei 14.133/2021, Art. 28, III',
        4 => 'Lei 14.133/2021, Art. 28, IV',
        5 => 'Lei 14.133/2021, Art. 28, V',
        6 => 'Lei 14.133/2021, Art. 74, I',
        7 => 'Lei 14.133/2021, Art. 74, II',
        8 => 'Lei 14.133/2021, Art. 74, III, a',
        9 => 'Lei 14.133/2021, Art. 74, III, b',
        10 => 'Lei 14.133/2021, Art. 74, III, c',
        11 => 'Lei 14.133/2021, Art. 74, III, d',
        12 => 'Lei 14.133/2021, Art. 74, III, e',
        13 => 'Lei 14.133/2021, Art. 74, III, f',
        14 => 'Lei 14.133/2021, Art. 74, III, g',
        15 => 'Lei 14.133/2021, Art. 74, III, h',
        16 => 'Lei 14.133/2021, Art. 74, IV',
        17 => 'Lei 14.133/2021, Art. 74, V',
        18 => 'Lei 14.133/2021, Art. 75, I',
        19 => 'Lei 14.133/2021, Art. 75, II',
        20 => 'Lei 14.133/2021, Art. 75, III, a',
        21 => 'Lei 14.133/2021, Art. 75, III, b',
        22 => 'Lei 14.133/2021, Art. 75, IV, a',
        23 => 'Lei 14.133/2021, Art. 75, IV, b',
        24 => 'Lei 14.133/2021, Art. 75, IV, c',
        25 => 'Lei 14.133/2021, Art. 75, IV, d',
        26 => 'Lei 14.133/2021, Art. 75, IV, e',
        27 => 'Lei 14.133/2021, Art. 75, IV, f',
        28 => 'Lei 14.133/2021, Art. 75, IV, g',
        29 => 'Lei 14.133/2021, Art. 75, IV, h',
        30 => 'Lei 14.133/2021, Art. 75, IV, i',
        31 => 'Lei 14.133/2021, Art. 75, IV, j',
        32 => 'Lei 14.133/2021, Art. 75, IV, k',
        33 => 'Lei 14.133/2021, Art. 75, IV, l',
        34 => 'Lei 14.133/2021, Art. 75, IV, m',
        35 => 'Lei 14.133/2021, Art. 75, V',
        36 => 'Lei 14.133/2021, Art. 75, VI',
        37 => 'Lei 14.133/2021, Art. 75, VII',
        38 => 'Lei 14.133/2021, Art. 75, VIII',
        39 => 'Lei 14.133/2021, Art. 75, IX',
        40 => 'Lei 14.133/2021, Art. 75, X',
        41 => 'Lei 14.133/2021, Art. 75, XI',
        42 => 'Lei 14.133/2021, Art. 75, XII',
        43 => 'Lei 14.133/2021, Art. 75, XIII',
        44 => 'Lei 14.133/2021, Art. 75, XIV',
        45 => 'Lei 14.133/2021, Art. 75, XV',
        46 => 'Lei 14.133/2021, Art. 75, XVI',
        47 => 'Lei 14.133/2021, Art. 78, I',
        48 => 'Lei 14.133/2021, Art. 78, II',
        49 => 'Lei 14.133/2021, Art. 78, III',
        50 => 'Lei 14.133/2021, Art. 74, caput',
        51 => 'Lei 14.284/2021, Art. 29, caput',
        52 => 'Lei 14.284/2021, Art. 24 § 1º',
        53 => 'Lei 14.284/2021, Art. 25 § 1º',
        54 => 'Lei 14.284/2021, Art. 34',
        55 => 'Lei 9.636/1998, Art. 11-C, I',
        56 => 'Lei 9.636/1998, Art. 11-C, II',
        57 => 'Lei 9.636/1998, Art. 24-C, I',
        58 => 'Lei 9.636/1998, Art. 24-C, II',
        59 => 'Lei 9.636/1998, Art. 24-C, III',
    ],

    'categoria_do_item_do_plano_de_contratacoes' => [
        1 => 'Material',
        2 => 'Serviço',
        3 => 'Obras',
        4 => 'Serviços de Engenharia',
        5 => 'Soluções de TIC',
        6 => 'Locação de Imóveis',
        7 => 'Alienação/Concessão/Permissão',
        8 => 'Obras e Serviços de Engenharia',
    ],

    'poder' => [
        'L' => 'Legislativo',
        'E' => 'Executivo',
        'J' => 'Judiciário',
        'N' => 'Não se aplica',
    ],

    'esfera' => [
        'F' => 'Federal',
        'E' => 'Estadual',
        'M' => 'Municipal',
        'D' => 'Distrital',
        'N' => 'Não se aplica',
    ],
];
